name: NoTargetAFK
version: '${version}'
main: io.github.brawaru.notargetafk.NoTargetAFKPlugin
api-version: 1.18
depend: [ Essentials ]
description: Makes entities not target AFK players
permissions:
  notargetafk.mobs-lose-track:
    default: true
    description: Whether all entities should lose track of player when they go AFK.
  notargetafk.mobs-dont-target:
    default: true
    description: Whether the player should not be targeted when they are AFK.